language: python

python:
    - "2.7"
    - "3.4"

services: postgresql

before_script:
    - psql -c 'create database travisci;' -U postgres

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - coverage run --rcfile=.coverage.rc manage.py test

after_success:
    coveralls --rcfile=.coverage.rc
